### PR TITLE
Add VSCode support

### PR DESCRIPTION
**Pull request by PhilippvK**
I am using a very similar approach for the FreeRTOS Emulator stuff as you will see later

### CODE REVIEW

**Comment by alxhoff** [comment]
will do this tomorrow :P
but thanks!

**Comment by alxhoff** [comment]
will this PR also solve #3?

**Comment by PhilippvK** [comment]
No, als already discussed before, there is no meaningful way to use a build directory when generating a eclipse project with cmake. I am sorry. Only thing I did in terms of Eclipse is attaching my Debug Configuration so that ESPL students can import it instead of having to fill out the fields by theirself.

**Comment by alxhoff** [comment]
I think it's time to drop eclipse support 😬

**Pull request merged**
